### ISSUE TITLE
bundle exec jekyll serve --config _config.yml,_config-dev.yml error

### ISSUE THREAD

**Issue by trip-itaka** [sergiokopplin/indigo#432]
I have followed instructions in readme. (With the excepton that i installed ruby dev kit instead of bundler, since bunder is now part of ruby)
i am working in visual studio code.

after executing 
`bundle exec jekyll serve --config _config.yml,_config-dev.yml`

i receive a whole bunch of errors
Traceback (most recent call last):
        31: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
        30: from C:/Ruby26-x64/bin/jekyll:23:in `load'
        29: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
        28: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
        27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in 
`require'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in 
`each'
        24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in 
`block in require'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in 
`each'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in 
`block (2 levels) in require'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in 
`require'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer.rb:11:in `<top (required)>'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer.rb:5:in `require_all'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer.rb:5:in `each'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer.rb:6:in `block in require_all'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer.rb:6:in `require'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer/url_validator.rb:3:in `<top (required)>'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/html-proofer-3.15.2/lib/html-proofer/url_validator.rb:3:in `require'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `require'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `require'  
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `require'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:145:in `block in f (LoadError)ld not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.

No idea what all this means!

**Comment by trip-itaka** [comment]
so i just needed to add libcurl.dll into ruby/bin directory
